Fixed the following bug:
Details:
When the MPJ Express runtime client (mpjrun) is invoked in the cluster
configuration, we intermittently see the following
ava.lang.NoClassDefFoundError: mpi/MPI exception: 

aamir@barq:~/projects/mpj-user> mpjrun.sh -np 64 HelloWorld
MPJ Express (0.35) is started in the multicore configuration
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:3
9)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImp
l.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at
runtime.starter.MulticoreStarter$1.run(MulticoreStarter.java:288)
at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.NoClassDefFoundError: mpi/MPI
at HelloWorld.main(HelloWorld.java:7)
... 6 more
Caused by: java.lang.ClassNotFoundException: mpi.MPI
at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
... 7 more